spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: MOVIEAPP
          uri: lb://MOVIEAPP
          predicates:
            - Path=/movie_app/**

        - id: USERAPP
          uri: lb://USERAPP
          predicates:
            - Path=/user_app/**
    discovery:
      enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    hostname: localhost

